# Generated by Django 5.1.2 on 2025-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_moduleregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='students_registered', to='itreporting.module'),
        ),
    ]
